{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Baseline Model.ipynb","provenance":[]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python","version":"3.9.7-final"},"accelerator":"GPU"},"cells":[{"cell_type":"code","source":["%cd '/content/drive/MyDrive/Colab Notebooks/Experiments/'"],"metadata":{"id":"lf3QBrLU9Ox6"},"execution_count":null,"outputs":[]},{"cell_type":"code","execution_count":32,"metadata":{"id":"tJYgeb0jtVfU","executionInfo":{"status":"ok","timestamp":1644233786205,"user_tz":-60,"elapsed":464,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"outputs":[],"source":["%matplotlib inline\n","import tensorflow as tf\n","import tensorflow.keras.backend as K\n","import tensorflow.keras as keras\n","from sklearn.metrics import confusion_matrix\n","from sklearn.model_selection import train_test_split\n","from sklearn.metrics import f1_score,precision_score,confusion_matrix,accuracy_score\n","from tensorflow.keras.applications import VGG16, ResNet50,VGG19,ResNet50V2,EfficientNetB0\n","from sklearn.preprocessing import StandardScaler\n","import IPython.display as ipd\n","import matplotlib.pyplot as plt\n","import librosa.display\n","from Visualize import *\n","from Preprocess import *\n","import soundfile as sf\n","from pathlib import *\n","import pandas as pd\n","import numpy as np\n","import librosa\n","import glob\n","import shutil\n","import os\n","import cv2\n","\n","os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'"]},{"cell_type":"code","source":["plt.rcParams['text.usetex'] = True\n","plt.rcParams['font.size'] = 12"],"metadata":{"id":"vPFoPu0pyV-W","executionInfo":{"status":"ok","timestamp":1644230736947,"user_tz":-60,"elapsed":370,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":2,"outputs":[]},{"cell_type":"code","source":["INPUT_PATH = Path('/net/store/cbc/projects/Pan troglodytes/audio_PH_dataset/PH/good_data/')\n","file_path =  '/net/store/cv/users/ybrima/scratch/data/Luango_Speaker/clip_loango.npz'\n","file_path2 =  '/net/store/cv/users/ybrima/scratch/data/Luango_Speaker/clip_loango_resized.npz'\n","BASE_PATH =  '/net/store/cv/users/ybrima/scratch/data/Luango_Speaker/'\n","FRAME_LENGHT =  1024\n","SAMPLE_RATE =  44100\n","HOP_LENGTH =  512"],"metadata":{"id":"DFhYVxV6yhZQ","executionInfo":{"status":"ok","timestamp":1644234172385,"user_tz":-60,"elapsed":378,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":3,"outputs":[]},{"cell_type":"code","source":["figures = Path('./Figures/')"],"metadata":{"id":"7lGZbMcBzDKt","executionInfo":{"status":"ok","timestamp":1644234185652,"user_tz":-60,"elapsed":358,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":4,"outputs":[]},{"cell_type":"code","source":["data =  np.load(file_path, allow_pickle=True)\n","X = data['x']\n","y = data['y']\n","Z =  data['z']\n","CLASSES = list(data['c'])"],"metadata":{"id":"DTH7NZ2Wzki4","executionInfo":{"status":"ok","timestamp":1644234178113,"user_tz":-60,"elapsed":2958,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":5,"outputs":[]},{"cell_type":"code","source":["def make_model(input_shape, output_nums):\n","    K.clear_session() # Clear previous models from memory.\n","    base_model = VGG16(weights=None, include_top=False, input_shape=input_shape)\n","    x = base_model.output\n","    x = keras.layers.Flatten()(x)\n","    x = keras.layers.Dense(output_nums, activation='softmax')(x)\n","    model = keras.Model(inputs=base_model.input, outputs=x)\n","    optim_params = dict(learning_rate = 0.003,momentum = 0.9394867962846013,decay = 0.0003)\n","    model.compile(loss='sparse_categorical_crossentropy',optimizer=keras.optimizers.SGD(**optim_params),metrics=[keras.metrics.SparseCategoricalAccuracy(name=\"accuracy\")]) #keras.metrics.SparseTopKCategoricalAccuracy(k=5, name='sparse_top_5_categorical_accuracy')\n","    return model"],"metadata":{"id":"nWPy4WPb1yCb","executionInfo":{"status":"ok","timestamp":1644234202305,"user_tz":-60,"elapsed":353,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":19,"outputs":[]},{"cell_type":"code","source":["X =  (X - X.mean(axis=0, keepdims=True))/X.std(axis=0,keepdims=True)"],"metadata":{"id":"wQi4T6N10z1f","executionInfo":{"status":"ok","timestamp":1644234204310,"user_tz":-60,"elapsed":427,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":7,"outputs":[]},{"cell_type":"code","source":["input_shape =  (X.shape[1],X.shape[2],1)\n","output_nums =  len(CLASSES)\n","X = X[...,np.newaxis]"],"metadata":{"id":"o1MvLIQp2mDA","executionInfo":{"status":"ok","timestamp":1644234205497,"user_tz":-60,"elapsed":4,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":8,"outputs":[]},{"cell_type":"code","source":["X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1, shuffle=True)"],"metadata":{"id":"S7t-tgG022Be","executionInfo":{"status":"ok","timestamp":1644234206845,"user_tz":-60,"elapsed":5,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":9,"outputs":[]},{"cell_type":"code","source":["model =  make_model(input_shape, output_nums)"],"metadata":{"id":"TE0tVX_N240e","executionInfo":{"status":"ok","timestamp":1644234209158,"user_tz":-60,"elapsed":549,"user":{"displayName":"Yusuf Brima","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiU8N2D1Lt9iKHQ1RhHL3Ocm1b0TnKwIkQb13gwHQ=s64","userId":"07941990287618148877"}}},"execution_count":24,"outputs":[]},{"cell_type":"code","source":["history =  model.fit(x=X_train,y=y_train, batch_size=8, epochs=20, validation_split=0.1,verbose=1 )\n","model.evaluate(x=X_test,y=y_test)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"1SlF-ITj3A_W","outputId":"2363ceb9-9df8-4585-8480-975feda430b6"},"execution_count":25,"outputs":[{"output_type":"stream","name":"stdout","text":"Epoch 1/20\n"},{"output_type":"error","ename":"UnknownError","evalue":" Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[node model/block1_conv1/Conv2D\n (defined at /net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py:231)\n]] [Op:__inference_train_function_4967]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node model/block1_conv1/Conv2D:\nIn[0] IteratorGetNext (defined at /net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py:866)\t\nIn[1] model/block1_conv1/Conv2D/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 619, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/events.py\", line 80, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n>>>     lambda f: self._run_callback(functools.partial(callback, future))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n>>>     ret = callback()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 814, in inner\n>>>     self.ctx_run(self.run)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 775, in run\n>>>     yielded = self.gen.send(value)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 358, in process_one\n>>>     yield gen.maybe_future(dispatch(*args))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n>>>     yield gen.maybe_future(handler(stream, idents, msg))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 536, in execute_request\n>>>     self.do_execute(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n>>>     if (await self.run_code(code, result,  async_=asy)):\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"<ipython-input-25-f7189c11b112>\", line 1, in <module>\n>>>     history =  model.fit(x=X_train,y=y_train, batch_size=8, epochs=20, validation_split=0.1,verbose=1 )\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py\", line 246, in call\n>>>     outputs = self.convolution_op(inputs, self.kernel)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py\", line 231, in convolution_op\n>>>     return tf.nn.convolution(\n>>> ","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-25-f7189c11b112>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m  \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0my_train\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m8\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalidation_split\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mverbose\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m \u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mevaluate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0my_test\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     59\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     60\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mUnknownError\u001b[0m:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n\t [[node model/block1_conv1/Conv2D\n (defined at /net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py:231)\n]] [Op:__inference_train_function_4967]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node model/block1_conv1/Conv2D:\nIn[0] IteratorGetNext (defined at /net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py:866)\t\nIn[1] model/block1_conv1/Conv2D/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 619, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/asyncio/events.py\", line 80, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/ioloop.py\", line 688, in <lambda>\n>>>     lambda f: self._run_callback(functools.partial(callback, future))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/ioloop.py\", line 741, in _run_callback\n>>>     ret = callback()\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 814, in inner\n>>>     self.ctx_run(self.run)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 775, in run\n>>>     yielded = self.gen.send(value)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 358, in process_one\n>>>     yield gen.maybe_future(dispatch(*args))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n>>>     yield gen.maybe_future(handler(stream, idents, msg))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 536, in execute_request\n>>>     self.do_execute(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/tornado/gen.py\", line 234, in wrapper\n>>>     yielded = ctx_run(next, result)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n>>>     if (await self.run_code(code, result,  async_=asy)):\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"<ipython-input-25-f7189c11b112>\", line 1, in <module>\n>>>     history =  model.fit(x=X_train,y=y_train, batch_size=8, epochs=20, validation_split=0.1,verbose=1 )\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py\", line 246, in call\n>>>     outputs = self.convolution_op(inputs, self.kernel)\n>>> \n>>>   File \"/net/store/cv/users/ybrima/miniconda3/envs/CV/lib/python3.9/site-packages/keras/layers/convolutional.py\", line 231, in convolution_op\n>>>     return tf.nn.convolution(\n>>> "]}]},{"cell_type":"code","source":["import tensorflow as tf\n","device_name = tf.test.gpu_device_name()\n","device_name"],"metadata":{"id":"0kMQez9L94FQ"},"execution_count":13,"outputs":[{"output_type":"execute_result","data":{"text/plain":"'/device:GPU:0'"},"metadata":{},"execution_count":13}]},{"cell_type":"code","execution_count":18,"metadata":{},"outputs":[{"output_type":"execute_result","data":{"text/plain":"(129, 87)"},"metadata":{},"execution_count":18}],"source":["D = librosa.amplitude_to_db(np.abs(librosa.stft(Z[0],n_fft=HOP_LENGTH//2, hop_length=HOP_LENGTH)), ref=np.max)\n","D.shape "]},{"cell_type":"code","execution_count":31,"metadata":{},"outputs":[{"output_type":"execute_result","data":{"text/plain":"(129, 87)"},"metadata":{},"execution_count":31}],"source":["D = librosa.stft(Z[0],hop_length=HOP_LENGTH,n_fft= FRAME_LENGHT//4)  # STFT of y\n","S_db = librosa.amplitude_to_db(np.abs(D), ref=np.max)\n","S_db.shape"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}]}